name: Quickstart

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.private == false
    uses: stellar/quickstart/.github/workflows/build.yml@main
    with:
      images: |
        [
          {
            "tag": "testing-with-pr",
            "inherit": "testing",
            "config": {
              "horizon_skip_protocol_version_check": true
            },
            "deps": [
              { "name": "core", "repo": "${{ github.event.pull_request.head.repo.full_name || github.repository }}", "ref": "${{ github.event.pull_request.head.sha || github.sha }}" }
            ],
            "tests": {
              "continue-on-error": false,
              "additional-tests": [
                { "arch": "amd64", "network": "testnet", "enable": "core,rpc,horizon" },
                { "arch": "amd64", "network": "pubnet", "enable": "core,rpc,horizon" }
              ]
            }
          }
        ]
      archs: '["amd64"]'
